<?php

$lang = array (

	"en" => array(
		"nav_home" => "Home",
		"nav_our_dogs" => "Our Dogs",
		"nav_males" => "Males",
		"nav_females" => "Females",
		"nav_puppies" => "Puppies",
		"nav_current_puppies" => "Current Puppies",
		"nav_mating_plan" => "Mating Plan",
		"nav_about_pug" => "About Pug",
		"nav_standard" => "Standard",
		"nav_maintenance" => "Maintenance",
		"nav_diseases" => "Diseases",
		"nav_contact_us" => "Contact Us",

		"footer_best_quality_dogs" => "Duma's Kennel - best quallity dogs - Mops/pug",

		"home_welcome" => "Welcome to the official website of <i>Duma's Kennel</i>",
		"home_subtitle" => "Best quallity for mops/pug dogs",
		"home_text1" => "Click on the links of Mops/Pug to find the pupppy that you wish",
		"home_text2" => "You can go through all the litters, males and females that were until now and are planned",
		"home_text3" => "You can click on each dog also to see it's pedigree",
		"home_text4" => "Enjoy your visit and don't hesitate to make a call or write an email",

		"pug_males_text1" => "Our dogs at Duma's Kennel",
		"pug_males_text2" => "MALE - mops of Duma's Kennel - scroll down for all males",

		"pug_females_text1" => "Our dogs at Duma's Kennel",
		"pug_females_text2" => "FEMALE - mops of Duma's Kennel - scroll down for all females",

		"click_for_details" => "Click for details",

		"details_title" => "Title",
		"details_parents" => "Parents",
		"details_gender" => "Gender",
		"details_male" => "male",
		"details_female" => "female",
		"details_date" => "Date",
		"details_pedigree" => "Pedigree",
		"details_galery" => "Photo Galery",

		"puppies_title" => "Puppies at Duma's Kennel",

		"litters_title" => "New matings at Duma's Kennel !!!!!!!",

		"standard_title" => "About Pug - Standard",
		"standard_p1" => "Pugs often are described as a lot of dog in a small space. These sturdy, compact dogs and are known as the clowns of the canine world because they have a great sense of humor and like to show off. Originally bred to be a lap dog, the Pug thrives on human companionship.",
		"standard_p2" => "Pugs are clowns at heart, but they carry themselves with dignity. Pugs are playful dogs, ready and able for games, but they are also lovers, and must be close to their humans. Pugs love to be the center of attention, and are heartsick if ignored.",
		"standard_p3" => 'Pugs are square and thickset, usually weighing no more than 20 pounds. Their heads are large and round, with large, round eyes. They have deep and distinct wrinkles on their faces. Legend has it that the Chinese, who mastered the breeding of this dog, prized these wrinkles because they resembled good luck symbols in their language. Especially prized were dogs with wrinkles that seemed to form the letters for the word "prince" in Chinese.',
		"standard_hilights" => "Highlights",
		"standard_p4" => 'Pugs can\'t tolerate high heat and humidity because of a short muzzle (air cools down when it passes through the noses of dogs with longer muzzles before entering the lungs). <span style="color:red">When your Pug is outdoors, watch him carefully for signs of overheating. Pugs are definitely housedogs and should not be kept outdoors.',
		"standard_p5" => "Because they are a small, quiet breed and are relatively inactive when indoors, they are a good choice for apartment dwellers.",
		"standard_p6" => "Despite their short coats, Pugs shed a lot.",
		"standard_p7" => "Pugs wheeze, snort and snore, loudly.",
		"standard_p8" => "Because their eyes are so prominent, Pugs are prone to eye injuries.",
		"standard_p9" => "Pugs are greedy eaters and will overeat if given the chance. Since they gain weight easily, they can quickly become obese if food intake isn't monitored carefully. <br/>Personality-wise, Pugs are happy and affectionate, loyal and charming, playful and mischievous. They are very intelligent, however, they can be willful, which makes training challenging.",
		"standard_p10" => "Pugs need human constant human companion. If you own a Pug, expect him to follow you around in the house, sit in your lap, and want to sleep in bed with you.",
		"standard_p11" => "Pug enthusiasts are a fun-loving bunch. They love Pug get-togethers, Pug parades, and dressing up their Pugs.",
		"standard_p12" => "To get a healthy dog, never buy a puppy from an irresponsible breeder, puppy mill, or pet store. Look for a reputable breeder who tests her breeding dogs to make sure they're free of genetic diseases that they might pass onto the puppies, and that they have sound temperaments.",
		"standard_history" => "History",
		"standard_p13" => "Pugs originated in China, dating back to the Han dynasty (B.C. 206 to A.D. 200). Some historians believe they are related to the Tibetan Mastiff. They were prized by the Emperors of China and lived in luxurious accommodations, sometimes even being guarded by soldiers.",
		"standard_p14" => 'Pugs are one of three types of short-nosed dogs that are known to have been bred by the Chinese: the Lion dog, the Pekingese, and the Lo-sze, which was the ancient Pug. Some think that the famous "Foo Dogs" of China are representations of the ancient Pug. Evidence of Pug-like dogs has been found in ancient Tibet and Japan.',
		"standard_p15" => "In the latter 1500s and early 1600s, China began trading with European countries. Reportedly, the first Pugs brought to Europe came with the Dutch traders, who named the breed Mopshond, a name still used today.",
		"standard_p16" => "Pugs quickly became favorites of royal households throughout Europe, and even played a role in the history of many of these families. In Holland, the Pug became the official dog of the House of Orange after a Pug reportedly saved the life of William, Prince of Orange, by giving him a warning that the Spaniards were approaching in 1572. When William of Orange (later called William III) went to England in 1688 with his wife, Mary II, to take the throne from James II, they brought their Pugs with them.",
		"standard_size" => "Size",
		"standard_p17" => "Pugs weigh between 14 and 18 pounds (6.3 – 9 kg male and female). Generally, they are 10 to 14 inches (25 – 36 cm) tall at the shoulder.",
		"standard_personality" => "Personality",
		"standard_p18" => "Always meet at least one of the parents — usually the mother is the one who's available — to ensure that they have nice temperaments that you're comfortable with. Meeting siblings or other relatives of the parents is also helpful for evaluating what a puppy will be like when he grows up.",
		"standard_p19" => "Like every dog, the Pug needs early socialization — exposure to many different people, sights, sounds, and experiences — when they're young. Socialization helps ensure that your Pug puppy grows up to be a well-rounded dog.",
		"standard_p20" => 'Source:<br>Read more at <a href="http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99" target="_blank">http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99</a>',

		"maintenance_title" => "About Pug - Maintenance",
		"maintenance_p1" => "Though playful and rambunctious, the Pug is a low-maintenance companion, making it ideal for older owners. Because they are a small, quiet breed and are relatively inactive when indoors, they are a good choice for apartment dwellers as well.",
		"maintenance_p2" => "Their compact package belies a great deal of energy, so expect to be entertained with some goofy antics if your Pug doesn't get a walk or some playtime. They are sensitive to heat and humidity, however, so if you live in a hot or humid environment, be sure your Pug doesn't spend too much time outside.",
		"maintenance_p3" => "Light sleepers may also want to invest in a pair of ear plugs — Pugs are prone to snore.",
		"maintenance_feeding" => "Feeding",
		"maintenance_p4" => "How much your adult dog eats depends on his size, age, build, metabolism, and activity level. Dogs are individuals, just like people, and they don't all need the same amount of food. It almost goes without saying that a highly active dog will need more than a couch potato dog. The quality of dog food you buy also makes a difference — the better the dog food, the further it will go toward nourishing your dog and the less of it you'll need to shake into your dog's bowl.",
		"maintenance_p5" => 'While the Pug\'s first love is human attention, his second love is food. These dogs love to eat, eat, eat. This, combined with their small stature, puts them at risk for obesity. <span style="color:red">As a Pug owner, you must show great restraint. Do not indulge him with food. Feed appropriate portions, limit treats and encourage exercise.</span>',
		"maintenance_coat" => "Coat Color And Grooming",
		"maintenance_p6" => "Even though the coats are short, Pugs are a double-coated breed. Pugs are typically fawn-colored or black. The fawn color can have different tints, such as apricot or silver, and all Pugs have a short, flat, black muzzle.",
		"maintenance_p7" => "The coat is short and smooth, but don't be deceived. Pugs shed like crazy, especially in summer. The wise Pug owner accepts this, and adjusts her wardrobe accordingly, wearing light-colored clothing that better hides hair.Following that, regular brushing and bathing helps keep the coat in good condition and shedding to a minimum. A monthly bath is sufficient, though some owners bathe their Pugs more frequently.",
		"maintenance_p8" => "Following that, regular brushing and bathing helps keep the coat in good condition and shedding to a minimum. A monthly bath is sufficient, though some owners bathe their Pugs more frequently.",
		"maintenance_p9" => "Regular nail trimming is essential, since these housedogs don't usually wear down their nails outdoors like active breeds do. It's a good idea to clean the Pug's ears every few weeks, as well.",
		"maintenance_p10" => "What requires special attention is the Pug's facial wrinkles. These folds are hotbeds for infection if allowed to become damp or dirty. The wrinkles must be dried thoroughly after bathing, and wiped out in-between baths. Some owners simply use a dry cotton ball; others use commercial baby wipes to wipe out the folds.",
		"maintenance_p11" => "Additionally, the Pug's bulging eyes need special attention. Because they protrude, the eyes are vulnerable to injury and irritation from soaps and chemicals.",
		"maintenance_p12" => "Like many small breeds, the Pug can be susceptible to gum disease. Regular brushing with a small, soft toothbrush and doggie toothpaste helps prevent this.",
		"maintenance_p13" => "Begin accustoming your Pug to being brushed and examined when he's a puppy. Handle his paws frequently — dogs are touchy about their feet — and look inside his mouth. Make grooming a positive experience filled with praise and rewards, and you'll lay the groundwork for easy veterinary exams and other handling when he's an adult.",
		"maintenance_p14" => "As you groom, check for sores, rashes, or signs of infection such as redness, tenderness, or inflammation on the skin, in the nose, mouth, and eyes, and on the feet. Eyes should be clear, with no redness or discharge. Your careful weekly exam will help you spot potential health problems early.",
		"maintenance_children" => "Children And Other Pets",
		"maintenance_p15" => "Pugs love kids. Though small, the Pug is not delicate like some toy breeds, so he is a good breed choice for families with children. However, children who want an active pet to retrieve balls or play soccer will be disappointed with a Pug. Adults should always supervise interactions between children and pets.",
		"maintenance_p16" => "Properly trained and socialized, the Pug enjoys the companionship of dogs, and can be trusted with cats, rabbits, and other animals.",
		"maintenance_p17" => 'Source:<br>Read more at <a href="http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99" target="_blank">http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99</a>',
		
		"diseases_title" => "About Pug - Diseases",
		"diseases_p1" => "Pugs are generally healthy, but like all breeds, they're prone to certain health conditions. Not all Pugs will get any or all of these diseases, but it's important to be aware of them if you're considering this breed.",
		"diseases_p2" => "If you're buying a puppy, find a good breeder who will show you health clearances for both your puppy's parents. Health clearances prove that a dog has been tested for and cleared of a particular condition.",
		"diseases_p3" => "<b>Corneal Ulcers:</b> Because his eyes are so large and prominent, the Pug's eyes can be injured easily or develop ulcers on the cornea (the clear part of the eye). If your Pug squints or the eyes look red and tear excessively, contact your vet immediately. Corneal ulcers usually respond well to medication, but if left untreated, can cause blindness or even rupture the eye.",
		"diseases_p4" => "<b>Dry Eye:</b> Keratoconjunctivitissicca and pigmentary keratitis are two conditions seen in Pugs. They can occur at the same time, or individually. Dry eye is caused when the eyes don't produce enough tears to stay moist. Your vet can perform tests to determine if this is the cause, which can be controlled with medication and special care. Pigmentarykeratits is a condition that causes black spots on the cornea, especially in the corner near the nose. If the pigment covers the eye, it can cause blindness. Your vet can prescribe medication that will help keep the eyes moist and dissolve the pigment. Both of these eye conditions require life-long therapy and care.",
		"diseases_p5" => "<b>Eye Problems:</b> Because their large eyes bulge, Pugs are prone to a variety of eye problems, including proptosis (the eyeball is dislodged from the eye socket and the eyelid clamps behind it); distichiasis (an abnormal growth of eyelashes on the margin of the eye, resulting in the eyelashes rubbing against the eye); progressive retinal atrophy (a degenerative disease of the retinal visual cells that leads to blindness); and entropion (the eyelid, usually the lower lid, rolls inward, causing the hair on the lid to rub on the eye and irritate it).",
		"diseases_p6" => "<b>Allergies:</b> Some Pugs suffer from a variety of allergies, ranging from contact to food allergies. If your Pug is licking at his paws or rubbing his face a great deal, suspect allergy and have him checked by your vet.",
		"diseases_p7" => "<b>Demodectic Mange:</b> Also called demodicosis, all dogs carry a little passenger called a demodex mite. The mother dog passes this mite to her pups in their first few days of life. The mite can't be passed to humans or other dogs; only the mother passes mites to her pups. Demodex mites live in hair follicles and usually don't cause any problems. If your Pug has a weakened or compromised immune system, however, it can develop demodectic mange. Demodectic mange can be localized or generalized. In the localized form, patches of red, scaly, skin with hair loss appears on the head, neck and forelegs. It's thought of as a puppy disease, and often clears up on its own. Even so, you should take your dog to the vet because it can turn into the generalized form of demodectic mange. Generalized demodectic mange covers the entire body and affects older puppies and young adult dogs. The dog develops patchy skin, bald spots, and skin infections all over the body. The American Academy of Veterinary Dermatology recommends neutering or spaying all dogs that develop generalized demodectic mange because there is a genetic link.",
		"diseases_p8" => "<b>Patellar Luxation:</b> The patella is the kneecap. Luxation means dislocation of an anatomical part (as a bone at a joint). Patellar luxation is when the knee joint (often of a hind leg) slides in and out of place, causing pain. This can be crippling, but many dogs lead relatively normal lives with this condition.",
		"diseases_p9" => "<b>Vaccination Sensitivity:</b> There are reports of Pugs suffering from sensitivity to routine vaccinations. Usually, symptoms include hives, facial swelling, soreness and lethargy. A dog that is sensitive to vaccines can develop complications or die, though this is rare. Watch your Pug carefully for a few hours after being vaccinated and call the vet if you notice anything unusual.",
		"diseases_p10" => 'Source:<br>Read more at <a href="http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99" target="_blank">http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99</a>',

		"contact_title" => "Contact Duma's Kennel",
		"contact_person" => "Duma Loredana - <i>pug breeder</i>",
		"contact_address" => "Address",
		"contact_phone" => "Phone",
		"contact_email" => "email",

	),

	"ro" => array(
		"nav_home" => "Acasă",
		"nav_our_dogs" => "Câinii Noștri",
		"nav_males" => "Masculi",
		"nav_females" => "Femele",
		"nav_puppies" => "Pui",
		"nav_current_puppies" => "Pui Actuali",
		"nav_mating_plan" => "Împerecheri",
		"nav_about_pug" => "Despre Pug",
		"nav_standard" => "Standard",
		"nav_maintenance" => "Întreținere",
		"nav_diseases" => "Boli",
		"nav_contact_us" => "Contactează-ne",

		"footer_best_quality_dogs" => "Duma's Kennel - câinii cei mai de calitate - pug",

		"home_welcome" => "Bine ați venit pe site-ul oficial <i>Duma's Kennel</i>",
		"home_subtitle" => "Câini pug de cea mai bună calitate",
		"home_text1" => "Accesați link-urile din meniu ca să găsiți cățelul preferat",
		"home_text2" => "Puteți vedea toți puii, masculi și femele, pe care îi avem deja, sau sunt planificați",
		"home_text3" => "Puteți da click pe fiecare câine pentru a-i vedea pedigree-ul",
		"home_text4" => "Pentru orice informație legată de cățeii noștri, nu ezitați să sunați sau să scrieți un email",

		"pug_males_text1" => "Câinii nostri la Duma's Kennel",
		"pug_males_text2" => "MASCULI - pugs la Duma's Kennel - derulați pentru a vedea toți masculii",

		"pug_females_text1" => "Câinii nostri la Duma's Kennel",
		"pug_females_text2" => "FEMELE - pugs la Duma's Kennel - derulați pentru a vedea toate femelele",

		"click_for_details" => "Click pentru detalii",
		
		"details_title" => "Titlu",
		"details_parents" => "Părinți",
		"details_gender" => "Gen",
		"details_male" => "mascul",
		"details_female" => "femelă",
		"details_date" => "Data",
		"details_pedigree" => "Pedigree",
		"details_galery" => "Galerie Foto",

		"puppies_title" => "Căței la Duma's Kennel",

		"litters_title" => "Împerecheri noi la Duma's Kennel !!!!!!!",

		"standard_title" => "Despre Mopsi - Standard",
		"standard_p1" => "Mopsii sunt adesea descrisi, ca fiind caini cu mult character bine definit. Acesti caini compacti si robusiti sunt cunoscuti drept bufonii lumii canine. Ei dau dovada de un simt al umorului si le place sa fie in centrul atentiei. Ei cauta si depind de compania omului, devin foarte atasati de stapanii lor.",
		"standard_p2" => "In ciuda acestei etichete de bufon, mopsii sunt caini mandri, jucausi, insa sunt si iubareti si foarte apropiati de oameni. ",
		"standard_p3" => 'Anatomia mopsului scoate in evidenta caracteristicile fizice proeminente, precum botul turtit si ochii bulbucati, pieptul robust si lat, precum si coada in forma de covrig. Mopsii au riduri adanci pe fata. Legenda chineza spune ca forma ridurilor de pe fata mopsului simbolizeaza norocul si seamana cu simbolul literei “print” din limba chineza.',
		"standard_hilights" => "Trasaturi specifice",
		"standard_p4" => 'Din cauza botului turiti, mopsii nu pot raci suficient de mult aerul. Din acest motiv, trebuie evitata expunerea lor in zile foarte calduroase. <span style="color:red">Cand mopsul e lasat in curte, trebuie sa il supravegheati constant pentru a evita supraincalzirea. Mopsii sunt caini de casa si apartament. Ei nu pot fi tinuti exlcusiv in curte.</span>',
		"standard_p5" => "Fiind caini de talie mica cu o fire mai linistita, sunt o optiune ideala pentru cei, care isi doresc un caine de companie si traiesc intr-un apartament.",
		"standard_p6" => "Desi au blana scurta, mopsi naparlesc mult.",
		"standard_p7" => "Mopsiirespira greu, stranuta (si stranut invers) si sfoarie destul de tare.",
		"standard_p8" => "Datorira ochilor proeminenti, mopsii sunt predispusi la accidentarea ochilor.",
		"standard_p9" => "Mopsii sunt lacomi, iar daca li se ofera mancare ei vor manca chiar daca nu mai pot. Tot din acest motiv, mopsii se pot ingrasa cu usurinta si pot deveni obezi. <br/>Personalitatea lor este una colorata. Mopsii sunt fericiti, bine dispusi si afectuosi si loiali. Sunt caini foarte inteligenti, dar pot fi si incapatanati uneori.",
		"standard_p10" => "Ei au nevoie sa fie in preajma omului. Daca va decideti sa cresteti un mops, va puteti astepta ca acesta sa va urmareasca peste to prin casa, sa va ceara afectiune si sa isi doreasca sa doarma in bratele dumneavoastra.",
		"standard_p11" => "Iubitorii de mopsi sunt oameni distractivi, deschisi si care rezoneaza cu caracterul puternic al acestor caini.",
		"standard_p12" => "Pentru a va asigura ca nu achizitionati un caine bolnav, recomandam sa nu achizitionati de la crescatori iresponsabili sau din magazinele de tip pet-shop. Cautati un crescator recunoscut, care se ocupa de caini si care testeaza parinti si puii pentru boli genetice.",
		"standard_history" => "Istoric",
		"standard_p13" => "Mopsul provine din dinastia Han (206 i.e.n.). Acesti caini au fost iubiti si foarte apreciati de catre familia regala si traiu adesea in conditii de lux, uneori erau chiar paziti de soldati.",
		"standard_p14" => 'Aristocrația chinezasi membri familiilor imperiale au manifestat mereu o anume slabiciune pentru cainii de talie mica, cu ochii mari și contrucție craniana brahicefalicasi se pare ca evoluția raselor pechinez, Spaniel Japonez (Chin) și mops se bazeaza pe un filon genetic comun, specialiștii opinand ca, de-a lungul timpului, au avut loc incrucisari succesive intre exemplarele acestor rase.',
		"standard_p15" => "La sfarsitul secolului al XV-lea si inceputul secolului al XVI-lea, cand marinarii olandezi, portughezi, spanioli și englezi au inițiat primele schimburi comerciale in zona, cainii de tip mops au fost remarcati pentru aspectul lor deosebit, nemaiintalnit in Europa. Olanda a fost prima tara europeana care i-a adoptat cu entuziasm, mopsii devenind repede favoritii liderilor politico-militari din epoca (Willem de Orania, poreclit Taciturnul, despre care legenda spune ca ar fi reusit sa evite un dezastru militar gratie vigilentei si latratului viguros al cainelui sau). Olandezii au ales sa-i denumeasca Mopshond. Dealtfel, in spatiul cultural de limba germanica acești caini sunt recunoscuti sub denumirea de Mops.",
		"standard_p16" => 'La finalul secolului al XVII-lea, odata cu accesul la tronul Angliei a lui William al III-lea de Orania (consortul reginei Mary a II-a), acesti caini au ajuns sa fie foarte apreciai in insulele de dincolo de Canalul Manecii si chiar au ajuns, in timp, ss contribuie la formarea altor rase (King Charles Spaniel, French Bulldog etc.). Pictori faimosi i-au imortalizat in operele lor: William Hogarth (celebrul tablou "House of Cards", ce infatiseaza mops jucand carti), Francisco Goya (intr-o opera realizata in anul 1785 si in care apar exemplare cu urechile cupate). Standardizarea rasei se produce incepand cu secolul al XVIII-lea.',
		"standard_size" => "Marime",
		"standard_p17" => "Mopsii au un corp robust si puternic. Greutatea lor variaza intre 6.3 – 9 kg (femela si mascul) iar inaltimea lor (la umeri) este de 25-36 cm (femela si mascul).",
		"standard_personality" => "Personalitatea",
		"standard_p18" => "Recomandam sa cunoasteti parinti puilor pe care doriti sa ii achizitionati pentru a va face o impresie despre personalitate parintilor. Astfel va puteti face o impresie si despre firea puilor.",
		"standard_p19" => "Simpatic, amuzant (are mereu o mina usor ingrijorata si nedumerita, sugerata de ridurile de pe frunte), afectuos si atasat de stapan și de familia acestuia, mopsul este un partener canin placut si reconfortant. Acești caini se impacabine cu copiii si accepta destul de usor strainii care se comporta prietenos. Deși va semnala prezența persoanelor straine prin latrat, se va obisnui repede cu prezența lor (ceea ce nu ii recomanda in rol de paznici de nadejde). Nu sunt prea dispusi la efort fizic, au o natura mai sedentara si sunt comozi din fire. Prefera jocurile si activitatile mai puțin dinamice, desfasurate pe suprafețe mici, in zone cunoscute. Prefera plimbarile linistite efectuate mai ales dimineata devreme si in orele serii, pentru ca nu rezista bine la caldura excesiva. Se dovedeșc adesea incapatanati si temperamentali, mai ales in absenta unui dresaj bine executat.",
		"standard_p20" => 'Sursa:<br>Citeste mai mult aici: <a href="http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99" target="_blank">http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99</a>',

		"maintenance_title" => "Despre Mopsi - Ingrijirea",
		"maintenance_p1" => "Mopsii sunt caini ce necesita putina ingrijire. Fiind caini de talie mica si fiind relativ inacitivi, sunt ideali pentru apartament.",
		"maintenance_p2" => "Totusi au nevoie de interactiune cu stapanul si timpul lor de joaca, respectiv minim doua plimbari pe zi. Sunt sensibili la caldura si umiditate crescuta.",
		"maintenance_p3" => "Mopsii sforaie, stranuta si fac o multime de sunete ciudate.",
		"maintenance_feeding" => "Hranirea",
		"maintenance_p4" => "Cantitatea de hrana oferita unui mops depinde de inaltimea sa, varsta, metabolismul si nivelul de actvitate. Este de la sine inteles ca un caine mai activ va consuma mai multa hrana decat unul mai putin activ. Calitatea hranei din comert variaza de la low-end la high-end. Pentru sanatatea cainelui dumneavoastra noi, recomandam hrana foarte buna spre high-end.",
		"maintenance_p5" => 'Desi mopsii isi iubesc stapanul, a doua iubire a lor e mancarea.Ei vor manca fara limite. Din acest motiv mopsii sunt mereu expusi riscului de a deveni obezi. <span style="color:red">Nu cedati privirilor intense care exprima o suferinta adanca si foame chinuitoare – mopsii pot fi foarte dramatici, atunci cand vine vorba de mancare. Nu le dati mai mult, decat portia lor recomandata!<br/>Recomandam un exercitiu regulat si limitarea recompenselor intre mese.</span>',
		"maintenance_coat" => "Blana si ingrijirea ei",
		"maintenance_p6" => "Desi au blana scurta, mopsii naparlesc mult, mai ales vara. Mopsii au doua straturi de blana.",
		"maintenance_p7" => "Coloarea cea mai raspandita la mopsi este culoarea bej si negru. Nuanta bej are derivate in apricot si argintiu. Indiferent de nuanta , toti mopsii au botul negru.",
		"maintenance_p8" => "O baie pe luna e suficienta. Periatul regulat ajuta in perioadele de naparlire.",
		"maintenance_p9" => "Unghiile trebuie taiate in mod regulat. Nefiind caini activi, inseamna ca nu reusesc sa isi toceasca unghiile suficient.",
		"maintenance_p10" => "Urechile trebuie curatate odata la saptamana.",
		"maintenance_p11" => "Multa atentie necesita ridurile mopsilor. Acestea trebuie curatate mereu, deoarece in ele se aduna multe impuritati, care pot produce iritatii si infectii. Cutele trebuie tinute uscate tot timpul.",
		"maintenance_p12" => "Mopsii, asemenea altor rase de talie mica, sunt predispusi la probleme cu gingiile. Periatul periodic e obligatoriu pentru a asigura o igiena dentara corespunzatoare.",
		"maintenance_p13" => "Obisnuiti-va mopsul cu periatul de la o varsta frageda. Mare atentie si rabdare cu labutele. Nu le place sa li se umble la labute. Pieptanatul si ingrijirea dintilor si a labutelor trebuie sa fie o experienta pozitiva pentru mops, usurand astfel procesul pe masura ce inainteaza in varsta.",
		"maintenance_p14" => "Cand ingrijiti mopsul si il pieptanati, aveti ocazia sa examinai cainele si observati eventuale rani sau probleme care nu se pot observa imediat cu ochiul liber. Totodata, e momentul ideal pentru a transmite iubire si afectiune.",
		"maintenance_children" => "Copiii si alte animale",
		"maintenance_p15" => "Mopsii iubesc copiii, desi sunt de talie mica nu sunt sensibili ca alt erase tip toy. Din acest motiv sunt caini ideali pentru familii cu copii. Copiii nu vor putea interactiona cu ei in sensul aportului si a jocului cu mingea, dar cu siguranta vor gasi activitati, care sa ii incante. Parintii trebuie sa supervizeze interactiunea cainilor cu copiii!",
		"maintenance_p16" => "Dresati timpuriu si socializati, mopsii se inteleg foarte bine cu alti caini si chiar si cu pisici, iepuri sau alte animale.",
		"maintenance_p17" => 'Sursa:<br>Citeste mai mult aici: <a href="http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99" target="_blank">http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99</a>',
		
		"diseases_title" => "Despre Pug - Boli si afectiuni",
		"diseases_p1" => "Mopsi sunt caini sanatosi in general, insa ca si orice alta rasa, sunt predispusi la unele boli si afectiuni. Nu e o regula, si nu toti mopsi vor avea aceste boli. E important sa cunoasteti si acest aspect, inainte de a deveni stapan de mops.",
		"diseases_p2" => "Va recomandam sa cautati un breeder responsabil, care verifica pui si parinti pentru eventuale probleme genetice.",
		"diseases_p3" => "<b>Corneal Ulcers:</b> Deoarece au ochii foarte proeminenti, mopsii isi accidenteaza des ochii si pot dezvolta Corneal Ulcers (partea alba a ochiului).",
		"diseases_p4" => "<b>Ochi uscati:</b> Keratoconjunctivitissicca si keratis pigmentar sunt doua boli ale ochiului des intalnite la mopsi. Aceste afectiuni pot aparea individual sau in acelasi timp. Sindromul ochilor uscati apare in clipa in care corpul nu mai produce suficiente lacrimi pentru a lubrifia ochiul. Recomandam sa consultati un veterinar. Ochiul uscat poate fi tratat. Din pacate ambele afectiuni necesita un tratament pentru tot restul vietii mopsului.",
		"diseases_p5" => "<b>Probleme generale cu ochii:</b> Avad ochii proeminenti, mopsii sunt perdispusi la probleme cu ochii. Un exemplu este proptosis  iesirea ochiului din soclu; distichiasis (o deformatie a ploapelor la marginile ochiului rezulatand in iritarea ochiului prin frecare; atropine retinala progresiva (degenerare trepata a retinei care duce la pierderea vazului) si entropion (pleoapa de regula ceea inferioara se incovoieste spre interior iar firele fine de pe ploapa irita globul ocular).",
		"diseases_p6" => "<b>Alergii:</b> Unii mopsi sufera de diferite forme de alergii. Unele sunt alergii la contact si la macare. Daca mopsul se freaca exagerat de mult la fata cu labutele sau isi linge des labutele (mai mult decat toaletarea lor) faceti o vizita la medicul veterinar pentru  analiza.",
		"diseases_p7" => "<b>Demodic Mange:</b> Toti cainii sunt purtatori de larva demodex. Larva e transmisa de la mama in primele zile dupa nastere. LARVA NU POATE FI TRANSMISA CATRE OM SAU ALTI CAINI. Larva traieste in foliculul de par si in mod general nu produce nici o afectiune.<br/>Daca sistemul imunitar a cainelui e scazut, larva poate provoca o iritatie severa din cauza acestei larve demodex. Iritatia poate fi una locala sau raspandita pe tot corpul. Izolat apare mai des in zona gatului si au forma ciculara de culoare rosiatica. E considerata o boala a puilor si ar trebui sa treaca de la sine. Totusi noi recomandam un consult veterinar. Chiar daca apare in locuri isolate acesta poate fi un indiciu pentru o stare generala afectata de demodex ceea ce poate fi foarte deranjant si suparator pentru catel.",
		"diseases_p8" => "<b>Luxatia patelara:</b> Patela este discul genunchiului la caini. Luxarea inseamana ca patella sare din loc. De regula apare la picioarele din spate. In unele cazuri aceasta luxatie provoaca dureri insa in ceea mai mare parte cainii nu sunt afectati. Se recomanda un consult veterinar pentru a stabilii gradul de luxatie. ",
		"diseases_p9" => "<b>Sensiblitate la vaccine:</b> Exista unele rapoarte izolate care ar indica o sensibilitate la vaccinare. Cele mai des intalnite sunt reactiile alergice care produc o umflare a fetei si a corpului. Fiti atenti la caine in urmatoarele ore dupa vaccinare. Daca vi se pare ca are un comportament apatic si incepe sa se umfle contactati de urgenta un veterinar.",
		"diseases_p10" => 'Sursa:<br>Citeste mai mult aici: <a href="http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99" target="_blank">http://dogtime.com/dog-breeds/pug#h5lej2YHbeKEjYk3.99</a>',	

		"contact_title" => "Contact Duma's Kennel",
		"contact_person" => "Duma Loredana - <i>pug breeder</i>",
		"contact_address" => "Adresa",
		"contact_phone" => "Telefon",
		"contact_email" => "email",

	)

);

?>